version: '3.8'

services:
  burgerorder:
    build:
      context: ./containers/burgerorder
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      DB_HOST: host.docker.internal  # Connect to the local MySQL
      DB_USER: root
      DB_PASSWORD: root
      DB_DATABASE: burgardatabase

  kitchenview:
    build:
      context: ./containers/kitchenview
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
