
services:
  burgerorder:
    build:
      context: ./containers/burgerorder
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db  
      DB_USER: postgres
      DB_PASSWORD: hello
      DB_DATABASE: burgardatabase

  kitchenview:
    build:
      context: ./containers/kitchenview
      dockerfile: Dockerfile
    ports:
      - "5001:5001"

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hello
      POSTGRES_DB: burgardatabase
    ports:
      - "5432:5432"
  