
services:
  burgerorder:
    build:
      context: ./containers/burgerorder
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db  
      DB_USER: postgres  # Update to the default PostgreSQL user
      DB_PASSWORD: hello  # Use the password you set for PostgreSQL
      DB_DATABASE: burgardatabase  # Database name

  kitchenview:
    build:
      context: ./containers/kitchenview
      dockerfile: Dockerfile
    ports:
      - "5001:5001"

  db:
    image: postgres:latest  # Use the PostgreSQL image
    restart: always
    environment:
      POSTGRES_USER: postgres  # Default PostgreSQL user
      POSTGRES_PASSWORD: hello  # Password for the PostgreSQL user
      POSTGRES_DB: burgardatabase  # Initial database to create
    ports:
      - "5432:5432"  # Expose PostgreSQL port
  